version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: spa-backend:latest
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: production
      PORT: 5000
      CORS_ORIGIN: http://localhost:3000
      MONGODB_URI: mongodb://mongo:27017/smart_products
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: gpt-4o-mini
      OPENAI_MAX_TOKENS: 400
      OPENAI_TEMPERATURE: 0.1
      OPENAI_TIMEOUT: 30000
      OPENAI_MAX_RETRIES: 3
    ports:
      - "5001:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Frontend will call /api which Nginx proxies to backend
        REACT_APP_API_URL: /api
    image: spa-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data:
  redis_data:


